### ISSUE TITLE
collector stuck forever

### ISSUE THREAD

**Issue by dormael** [darimuri/coll-news#7]
```
2022/01/05 04:28:11.173161 coll.go:177: collect news daum mobile to coll_dir/daum/mobile
2022/01/05 04:28:11.173302 factory.go:42: new collector with option {/usr/bin/chromium-browser coll_dir/daum/mobile/dump/2022 /tmp/rod/daum/mobile 1 true false}
2022/01/05 04:28:11.331620 coll.go:231: get top news list 0 < 10

2022/01/07 22:44:17.282626 coll.go:241: failed to get top news list for panic 'cdp connection closed: context canceled' from stack:
goroutine 360970 [running]:
runtime/debug.Stack(0xc0127657c0, 0xc01a338690, 0x27)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/darimuri/coll-news/pkg/util.PanicAsError(0xbc2b40, 0xc0127657c0, 0xc0127657c0, 0xc011f4a000)
	/coll-news/pkg/util/flow.go:15 +0x186
github.com/darimuri/coll-news/pkg/adaptor.(*Adaptor).GetTopNewsList.func1(0xc000303bb0)
	/coll-news/pkg/adaptor/adaptor.go:96 +0x43
panic(0xbc2b40, 0xc0127657c0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/darimuri/go-lib/rodtemplate.(*PageTemplate).WaitLoad(0xc017ab4190)
	/go/pkg/mod/github.com/darimuri/go-lib@v0.1.8/rodtemplate/page.go:171 +0xd8
github.com/darimuri/go-lib/rodtemplate.(*PageTemplate).WaitLoadAndIdle(0xc017ab4190)
	/go/pkg/mod/github.com/darimuri/go-lib@v0.1.8/rodtemplate/page.go:122 +0x51
github.com/darimuri/coll-news/pkg/adaptor.(*Adaptor).GetTopNewsList(0xc01a6f40c0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/coll-news/pkg/adaptor/adaptor.go:100 +0xbe
github.com/darimuri/coll-news/cmd/coll.collectAndSave(0xc00021c0c0, 0x14, 0x7ffcf5d27b36, 0x4, 0x7ffcf5d27b2c, 0x6, 0x0, 0x0)
	/coll-news/cmd/coll/coll.go:235 +0x9e6
github.com/darimuri/coll-news/cmd/coll.collect.func2(0xc0001fa180, 0xc00021c0c0, 0x14)
	/coll-news/cmd/coll/coll.go:155 +0x69
created by github.com/darimuri/coll-news/cmd/coll.collect
	/coll-news/cmd/coll/coll.go:154 +0x3ff

```

**Comment by dormael** [comment]
```
goroutine 0 [idle]:
runtime.futex(0x14acf88, 0x80, 0x0, 0x0, 0x0, 0x7febd3d8a008, 0x7ffe5a756988, 0x425e42, 0x7ffe5a756950, 0x40a8bf, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:535 +0x21
runtime.futexsleep(0x14acf88, 0x7ffe00000000, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os_linux.go:44 +0x46
runtime.notesleep(0x14acf88)
	/usr/local/go/src/runtime/lock_futex.go:151 +0x9f
runtime.stoplockedm()
	/usr/local/go/src/runtime/proc.go:2068 +0x88
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2469 +0x485
runtime.park_m(0xc0002f4300)
	/usr/local/go/src/runtime/proc.go:2610 +0x9d
runtime.mcall(0x0)
	/usr/local/go/src/runtime/asm_amd64.s:318 +0x5b

goroutine 1 [select, 1729 minutes]:
github.com/go-rod/rod/lib/cdp.(*Client).Call(0xc0002fa100, 0xf438e0, 0xc000026050, 0xc0002521a0, 0x20, 0xcc9fdb, 0x16, 0xc8b320, 0xc000338480, 0x0, ...)
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/lib/cdp/client.go:157 +0x59a
github.com/go-rod/rod.(*Browser).Call(0xc000368000, 0xf438e0, 0xc000026050, 0xc0002521a0, 0x20, 0xcc9fdb, 0x16, 0xc8b320, 0xc000338480, 0x409f2a, ...)
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/browser.go:241 +0xb7
github.com/go-rod/rod.(*Page).Call(0xc0000ae8c0, 0xf438e0, 0xc000026050, 0xc0002521a0, 0x20, 0xcc9fdb, 0x16, 0xc8b320, 0xc000338480, 0x1, ...)
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/page.go:697 +0x9e
github.com/go-rod/rod/lib/proto.call(0xcc9fdb, 0x16, 0xc8b320, 0xc000338480, 0xb370a0, 0xc000263690, 0xf34ee0, 0xc0000ae8c0, 0x0, 0x0)
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/lib/proto/interface.go:63 +0x145
github.com/go-rod/rod/lib/proto.RuntimeCallFunctionOn.Call(...)
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/lib/proto/runtime.go:685
github.com/go-rod/rod.(*Page).evaluate(0xc0000ae8c0, 0xc000485580, 0xc000076000, 0xc0004854e8, 0x40c618)
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/page_eval.go:183 +0x1fb
github.com/go-rod/rod.(*Page).Evaluate(0xc0000ae8c0, 0xc0001d1580, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/page_eval.go:140 +0x5a
github.com/go-rod/rod.(*Page).WaitLoad(0xc0000ae8c0, 0x0, 0x0)
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/page.go:544 +0x1f1
github.com/darimuri/coll-news/pkg/adaptor.(*Adaptor).Open(0xc000338240, 0xcc9685, 0x15)
	/coll-news/pkg/adaptor/adaptor.go:58 +0x101
github.com/darimuri/coll-news/pkg/daum.(*Collector).Top(0xc00017e038)
	/coll-news/pkg/daum/coll.go:24 +0x43
github.com/darimuri/coll-news/cmd/coll.collectAndSave(0xc000253380, 0x14, 0x7ffe5a757d85, 0x4, 0x7ffe5a757d7b, 0x6, 0x1, 0x0, 0x0)
	/coll-news/cmd/coll/coll.go:240 +0x97f
github.com/darimuri/coll-news/cmd/coll.collect(0x0, 0x0)
	/coll-news/cmd/coll/coll.go:149 +0x7d4
github.com/darimuri/coll-news/cmd/coll.glob..func1(0x149bdc0, 0xc0001c8460, 0x0, 0xe, 0x0, 0x0)
	/coll-news/cmd/coll/coll.go:95 +0x22
github.com/spf13/cobra.(*Command).execute(0x149bdc0, 0xc0001c8380, 0xe, 0xe, 0x149bdc0, 0xc0001c8380)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x149c2c0, 0xc000289f40, 0x2, 0x2)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/coll-news/cmd/main.go:25 +0x7d

goroutine 6 [syscall, 1729 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 8 [IO wait, 1729 minutes]:
internal/poll.runtime_pollWait(0x7febd1b10f08, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc000184118, 0x72, 0x0, 0x0, 0xcbf4eb)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc000184100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1f8
net.(*netFD).accept(0xc000184100, 0x50, 0x50, 0xc000092c70)
	/usr/local/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc000176d20, 0xc000092ca0, 0x477950, 0x30)
	/usr/local/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).AcceptTCP(0xc000176d20, 0x7febd3d7dd98, 0x0, 0x55faa7067b64ec9f)
	/usr/local/go/src/net/tcpsock.go:248 +0x47
github.com/labstack/echo.tcpKeepAliveListener.Accept(0xc000176d20, 0x40c618, 0x30, 0xc4e340, 0x1)
	/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/echo.go:767 +0x2f
net/http.(*Server).Serve(0xc0001c8620, 0xf40920, 0xc00017e050, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2896 +0x280
github.com/labstack/echo.(*Echo).StartServer(0xc00000a780, 0xc0001c8620, 0xc000092fb8, 0x1)
	/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/echo.go:663 +0x385
github.com/labstack/echo.(*Echo).Start(...)
	/go/pkg/mod/github.com/labstack/echo@v3.3.10+incompatible/echo.go:604
github.com/darimuri/coll-news/cmd/coll.collect.func1(0xc00000a780)
	/coll-news/cmd/coll/coll.go:133 +0x235
created by github.com/darimuri/coll-news/cmd/coll.collect
	/coll-news/cmd/coll/coll.go:130 +0x60

goroutine 39 [IO wait, 1729 minutes]:
internal/poll.runtime_pollWait(0x7febd1b10af8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0002fa018, 0x72, 0x500, 0x5ff, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0002fa000, 0xc000118c01, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0002fa000, 0xc000118c01, 0x5ff, 0x5ff, 0xc0005fdd88, 0x443f9c, 0x600)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000354008, 0xc000118c01, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x68
encoding/json.(*Decoder).refill(0xc000194000, 0xa, 0x9)
	/usr/local/go/src/encoding/json/stream.go:161 +0xeb
encoding/json.(*Decoder).readValue(0xc000194000, 0x0, 0x0, 0x1)
	/usr/local/go/src/encoding/json/stream.go:136 +0x1dc
encoding/json.(*Decoder).Decode(0xc000194000, 0xb3a560, 0xc0001266c0, 0x0, 0x0)
	/usr/local/go/src/encoding/json/stream.go:63 +0x79
github.com/ysmood/leakless.(*Launcher).serve.func1(0xf41960, 0xc00000c620, 0xc00035e1e0, 0xc0000224e0, 0x20)
	/go/pkg/mod/github.com/ysmood/leakless@v0.7.0/leakless.go:99 +0x371
created by github.com/ysmood/leakless.(*Launcher).serve
	/go/pkg/mod/github.com/ysmood/leakless@v0.7.0/leakless.go:74 +0xb6

goroutine 40 [IO wait, 1729 minutes]:
internal/poll.runtime_pollWait(0x7febd1b10d68, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc00002a438, 0x72, 0x8001, 0x8000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00002a420, 0xc00015e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
os.(*File).read(...)
	/usr/local/go/src/os/file_unix.go:259
os.(*File).Read(0xc00000e038, 0xc00015e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file.go:116 +0x71
io.copyBuffer(0xf35520, 0xc00000c860, 0xf35a60, 0xc00000e038, 0xc00015e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:402 +0x122
io.Copy(...)
	/usr/local/go/src/io/io.go:364
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:311 +0x63
os/exec.(*Cmd).Start.func1(0xc0000b6000, 0xc00000c920)
	/usr/local/go/src/os/exec/exec.go:435 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:434 +0x608

goroutine 41 [IO wait, 1729 minutes]:
internal/poll.runtime_pollWait(0x7febd1b10bc8, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc00002a4f8, 0x72, 0x8001, 0x8000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00002a4e0, 0xc000156000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
os.(*File).read(...)
	/usr/local/go/src/os/file_unix.go:259
os.(*File).Read(0xc00000e050, 0xc000156000, 0x8000, 0x8000, 0x52, 0x0, 0x0)
	/usr/local/go/src/os/file.go:116 +0x71
io.copyBuffer(0xf35520, 0xc00000c8a0, 0xf35a60, 0xc00000e050, 0xc000156000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:402 +0x122
io.Copy(...)
	/usr/local/go/src/io/io.go:364
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:311 +0x63
os/exec.(*Cmd).Start.func1(0xc0000b6000, 0xc00000c9e0)
	/usr/local/go/src/os/exec/exec.go:435 +0x27
created by os/exec.(*Cmd).Start
	/usr/local/go/src/os/exec/exec.go:434 +0x608

goroutine 42 [syscall, 1729 minutes]:
syscall.Syscall6(0xf7, 0x1, 0x12, 0xc0001ae618, 0x1000004, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc0000242d0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/wait_waitid.go:31 +0x98
os.(*Process).wait(0xc0000242d0, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/exec_unix.go:22 +0x39
os.(*Process).Wait(...)
	/usr/local/go/src/os/exec.go:125
os/exec.(*Cmd).Wait(0xc0000b6000, 0x0, 0x0)
	/usr/local/go/src/os/exec/exec.go:501 +0x60
github.com/go-rod/rod/lib/launcher.(*Launcher).Launch.func1(0xc0000b6000, 0xc000364000)
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/lib/launcher/launcher.go:376 +0x2b
created by github.com/go-rod/rod/lib/launcher.(*Launcher).Launch
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/lib/launcher/launcher.go:375 +0x24a

goroutine 47 [select, 1729 minutes]:
github.com/go-rod/rod/lib/cdp.(*Client).consumeMsg(0xc0002fa100)
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/lib/cdp/client.go:181 +0x12e
created by github.com/go-rod/rod/lib/cdp.(*Client).Connect
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/lib/cdp/client.go:115 +0xe2

goroutine 15 [chan receive, 1729 minutes]:
github.com/go-rod/rod/lib/cdp.(*WebSocket).Connect.func1(0xf438a0, 0xc0001a22c0, 0xf4a2c0, 0xc00000e168)
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/lib/cdp/websocket.go:58 +0x48
created by github.com/go-rod/rod/lib/cdp.(*WebSocket).Connect
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/lib/cdp/websocket.go:57 +0x1ab

goroutine 48 [IO wait, 1729 minutes]:
internal/poll.runtime_pollWait(0x7febd1b10a28, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0002fa318, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0002fa300, 0xc00010d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0002fa300, 0xc00010d000, 0x1000, 0x1000, 0xc00060cc00, 0x3, 0xc000617ed0)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00000e168, 0xc00010d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x68
bufio.(*Reader).fill(0xc0001b6a80)
	/usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).ReadByte(0xc0001b6a80, 0x400, 0xc000617e84, 0x0)
	/usr/local/go/src/bufio/bufio.go:252 +0x39
github.com/go-rod/rod/lib/cdp.(*WebSocket).Read(0xc0001b69c0, 0xc000617e80, 0x2, 0x1, 0x0, 0x0)
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/lib/cdp/websocket.go:132 +0x44
github.com/go-rod/rod/lib/cdp.(*Client).readMsgFromBrowser(0xc0002fa100)
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/lib/cdp/client.go:209 +0x8a
created by github.com/go-rod/rod/lib/cdp.(*Client).Connect
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/lib/cdp/client.go:117 +0x104

goroutine 65 [chan receive, 1729 minutes]:
github.com/go-rod/rod.(*Browser).initEvents.func1(0xc000368000)
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/browser.go:439 +0xd5
created by github.com/go-rod/rod.(*Browser).initEvents
	/go/pkg/mod/github.com/go-rod/rod@v0.101.8/browser.go:437 +0xb4

```
