### ISSUE TITLE
daum pc always fail to collect

### ISSUE THREAD

**Issue by dormael** [darimuri/coll-news#8]
```
2022/02/02 14:05:01.593514 coll.go:177: collect news daum pc to coll_dir/daum/pc
2022/02/02 14:05:01.593728 factory.go:42: new collector with option {/usr/bin/chromium-browser coll_dir/daum/pc/dump/2022 /tmp/rod/daum/pc 1 true false}
2022/02/02 14:05:01.833803 coll.go:231: get top news list 0 < 10
2022/02/02 14:05:05.699611 coll.go:254: get news home news list 0 < 10
2022/02/02 14:05:06.772271 coll.go:264: failed to get news home news list for panic '#cSub block is missing' from stack:
goroutine 35 [running]:
runtime/debug.Stack(0xc011962bc0, 0xc011847540, 0x16)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/darimuri/coll-news/pkg/util.PanicAsError(0xb8e160, 0xc011962bc0, 0xc011962bc0, 0x7efc2a4a0b28)
	/coll-news/pkg/util/flow.go:15 +0x186
github.com/darimuri/coll-news/pkg/adaptor.(*Adaptor).GetNewsHomeNewsList.func1(0xc0001b5bb0)
	/coll-news/pkg/adaptor/adaptor.go:120 +0x43
panic(0xb8e160, 0xc011962bc0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/darimuri/go-lib/rodtemplate.(*PageTemplate).SelectOrPanic(0xc00000fbc0, 0xcaf1b6, 0x5, 0x14a5f70)
	/go/pkg/mod/github.com/darimuri/go-lib@v0.1.8/rodtemplate/page.go:317 +0x16f
github.com/darimuri/coll-news/pkg/daum/pc.(*pc).GetNewsHomeNewsList(0x14a5f70, 0xc00000fbc0, 0xc00025e080, 0x1a, 0xcaf006, 0x4, 0xc076a2209f53527e, 0x161b98f2d, 0x1489260, 0xc000282f60, ...)
	/coll-news/pkg/daum/pc/pc.go:36 +0x7d
github.com/darimuri/coll-news/pkg/adaptor.(*Adaptor).GetNewsHomeNewsList(0xc00025a360, 0x0, 0x0, 0x0, 0x0, 0x0)
	/coll-news/pkg/adaptor/adaptor.go:136 +0x36a
github.com/darimuri/coll-news/cmd/coll.collectAndSave(0xc0001fe160, 0x10, 0x7ffcabf53b36, 0x4, 0x7ffcabf53b30, 0x2, 0x0, 0x0)
	/coll-news/cmd/coll/coll.go:258 +0xc50
github.com/darimuri/coll-news/cmd/coll.collect.func2(0xc0001e0120, 0xc0001fe160, 0x10)
	/coll-news/cmd/coll/coll.go:155 +0x69
created by github.com/darimuri/coll-news/cmd/coll.collect
	/coll-news/cmd/coll/coll.go:154 +0x3ff

```

**Comment by dormael** [comment]
https://news.daum.net/

news home changed a lot
